### PR TITLE
More complete types, custom error handler, and fix a deadlock

### PR DESCRIPTION
**Pull request by alexmv**
Fixes: #33, #15, #42 respectively.

### CODE REVIEW

**Comment by Fatal1ty** [comment]
@alexmv

Many thanks! I'll do my best to look into it this week.

**Comment by alexmv** [comment]
Gentle ping on this?

**Comment by Fatal1ty** [comment]
@alexmv

Sorry for this delay. I've looked through your PR and must say, it looks great! The changes you have made are well thought out and implemented cleanly. Thank you for addressing three issues which we can close now!

**Comment by Fatal1ty** [comment]
I will prepare release notes shortly and publish a new version on pypi.

**Comment by Fatal1ty** [comment]
Release 3.0 is ready 🎉

https://pypi.org/project/aioapns/

**Pull request merged**
