### PR TITLE
APNS auth_key authorization support

### PR DESCRIPTION
**Pull request by kukosk**
@vitalliykashuta added support for auth_key authorization, don't we want to merge this in?

### CODE REVIEW

**Comment by Jc2k** [comment]
Any chance that this could be merged?

**Comment by Fatal1ty** [comment]
At least we have to ask @vitalliykashuta whether he wants to contribute.

**Comment by Fatal1ty** [comment]
Just for information. I am going to implement token based authorization in my own way as soon as possible.

**Comment by Fatal1ty** [comment]
I implemented token based connection in the version 1.6.

**Pull request closed without merging**
