### PR TITLE
fix: limit pyjwt version under 2.0.0

### PR DESCRIPTION
**Pull request by holyachon**
Hello. 
At first, thank you for developing cool library. I'm using it well :)
And also I am sorry for my poor English 😭 

I found issue #21, and I also had a trouble with pyjwt 2.0.0.

In my opinion, there are two options to fix it.
a) fix the code with using pyjwt 2.0.0 (ex. remove `.decode('ascii')` ) 
b) freeze version.

I think option a is better than b in the long term, but i'm not sure that just removing `.decode` has no side effects.

So finally i decided to freeze version to work well right now, and then next we can do option b.

If someone gives me a guide to check side effect of option b, i'm willing to try it.

Thank you :)

### CODE REVIEW

**Comment by Fatal1ty** [comment]
Hi @holyachon. Can you test `aioapns` with PyJWT>=2.0.0 and removed `.decode('ascii')`? I want to update requirements but I don't have a developer account at the moment to test it properly.

**Comment by holyachon** [comment]
> Hi @holyachon. Can you test `aioapns` with PyJWT>=2.0.0 and removed `.decode('ascii')`? I want to update requirements but I don't have a developer account at the moment to test it properly.

@Fatal1ty Hello. I tested sending notification with pyjwt 2.0.0 removing `decode('ascii')` and it returns `status == 200`, which is also same as pyjwt 1.7.1 with `decode('ascii')`. it seems to work well.

But i checked changelog of pyjwt. It says since 2.0.0, pyjwt drops support for python 2. (https://github.com/jpadilla/pyjwt/releases/tag/2.0.0)

Does aioapns have to support python 2 compatibility? i think it depends on your choice.

**Comment by Fatal1ty** [comment]
Sorry for delayed answer. This library hasn't had support for python 2 so it's not a problem to update all the dependencies. But since PyJWT stopped supporting 3.5 I decided to do the same. Thank you for you help!

**Comment by holyachon** [comment]
@Fatal1ty Thank you for your answer and fixing :)

**Pull request closed without merging**
